from .define import InstructionDefine
from .halt import InstructionHalt
from .jmp import InstructionJmp
from .jng import InstructionJNG
from .jnz import InstructionJNZ
from .jeq import InstructionJEQ
from .jne import InstructionJNE
from .move import InstructionMoveByte
from .noop import InstructionNoOp
from .cmp import InstructionCMPByte
